# Generated by Django 4.1.7 on 2023-03-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria2', '0003_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
